### ISSUE TITLE
GAT for pubmed 

### ISSUE THREAD

**Issue by abhigoku10** [hbkt/gat-pytorch#1]
@marblet  hi thanks for sharing the code have u tested GAT for pubmed dataset i am getting error only for pubmed dataset for your source code , can you let me kwn if its working for you

**Comment by marblet** [comment]
I could run the code with Pubmed dataset on Python 3.6, PyTorch 1.6.
What kind of error did you catch?

**Comment by abhigoku10** [comment]
@marblet  i am getting  Runtime CUDA errror  failed to allocate memory  and at the line  x = torch.cat([att(x, edge_list) for att in self.attentions], dim=1) i am able to run the other dataset like cora and citeseer

**Comment by marblet** [comment]
@abhigoku10 
I understand. Which do you use, GAT or SPGAT?
If you use GAT, we will get such an error because of out of memory on CUDA.
If so, please use SPGAT, which reduces wasting memory.

**Comment by abhigoku10** [comment]
@marblet  i used GAT , i there any way i can run GAT on pubmed ??

**Comment by marblet** [comment]
@abhigoku10 You can run GAT if you use multiple GPUs and allocate the attention matrices to them.
